function commandn
	switch $argv
        case "a"
        case "b"
        case "c"
        case "d"
        case "e"
        case "f"
        case "g"
        case "h"
        case "i"
        case "j"
        case "k"
        case "l"
        case "m"
        case "n"
        case "o"
        case "p"
        case "q"
            set thecommand "i3-msg kill"
        case "r"
        case "s"
        case "t"
        case "u"
        case "v"
        case "w"
        case "x"
        case "y"
        case "z"
    end
end
